repos:
  - repo: local
    hooks:
      - id: dedupe-url-and-check-duplicate-names
        name: Dedupe URL and check duplicate Names
        entry: .github/scripts/dedupe_url_and_check_duplicate_names.sh
        language: script
        types: [jsonl]
        stages: [commit]
        verbose: true
        pass_filenames: false
        fail_fast: false 